#import "system-tables/er-room.typ": er_room_system_table
#import "system-tables/bank.typ": bank_system_table
#import "system-tables/phoneline.typ": phoneline_system_table
#import "system-tables/hotel.typ": hotel_system_table
#import "system-tables/lathe-workshop.typ": lathe_workshop_system_table
#import "system-tables/car-painting.typ": car_painting_system_table
#import "system-tables/hospital.typ": hospital_system_table
#import "system-tables/emergency.typ": emergency_answer_system_table
#import "problem-tables-numbers/problem-9.typ": *
