#import "./problem-tables-numbers/table-styles.typ" : *
#import "./non-congruential-algorithms/middle-square-method.typ" : *
#import "./non-congruential-algorithms/middle-product-method.typ" : *
#import "./non-congruential-algorithms/constant-multiplier-method.typ" : *
#import "./congruential-linear-algorithms/linear-congruential-method.typ" : *
#import "./congruential-linear-algorithms/multiplicative-congruential-method.typ" : *
#import "./congruential-linear-algorithms/additive-congruential-method.typ" : *
#import "./congruential-non-linear-algorithms/quadratic-congruential-method.typ" : *
#import "./congruential-non-linear-algorithms/blum-blum-shub-method.typ" : *
#import "./random-numbers-properties/random-numbers-average.typ" : *
#import "./random-numbers-properties/random-numbers-variance.typ" : *
#import "./random-numbers-properties/random-numbers-independence.typ" : *
